### ISSUE TITLE
Enable Display name for all previous year submission

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#319]
- [ ] Enable display name configuration in survey editor
- [ ] Only Input and single option questions can be marked as display name questions
- [ ] The concatenation of the display name string will represent the ordering of the questions
- [ ] Show display name in saved submission and previous year submissions dropdown. If no question is configured , display question name in these dropdowns along with date of save/submission

**Comment by wayangalihpratama** [comment]
block by #308 
- need to wait the migration

**Comment by wayangalihpratama** [comment]
**Todo**
Note: follow above condition
- [ ] Create a migration to add "meta" column to question table
- [ ] Modify question model, crud, routes, and test
- [ ] Modify QuestionSetting component, add checkbox to set input/single option question as datapoint/display name
- [ ] Generate datapoint/display name when save/submit submission
- [ ] Load datapoint/display name to saved submission and previous year submission dropdown.

**Comment by wayangalihpratama** [comment]
Hi @joycarpediem , 
For this point "If no question is configured , display question name in these dropdowns along with date of save/submission"
Did you mean to show form name if no question configured ?

**Comment by joycarpediem** [comment]
@wayangalihpratama , if no display name question is configured then it should function as it is doing now
