### ISSUE TITLE
Disable delete survey if has submission on manage survey

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/isco#357]
**Todo**
- [x] Add disable delete exception if the survey has submission on backend
- [x] Add `disableDelete` param to form list endpoint on manage survey
- [x] Disable delete button on frontend if has submission
